Coffee Machine Project
ikalegin/NIX_Java_education_Kalegin_Ilya pull request #3
Opened 2021-10-24 13:59 UTC by ikalegin

Coffee Machine Project

Coffee Machine Project - Stage 1

Coffee Machine Project - Stage 2

Coffee Machine Project - Stage 3

Coffee Machine Project - Stage 4

Coffee Machine Project - Stage 5

Coffee Machine Project - Stage 6

2021-10-31 10:57 UTC, maxsomochkin requested changes

2021-10-31 10:57 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +        } else if (coffeeChoice == 2) { // latte
Рекомендую вынести варианты coffeChoice как константы в  начало класса:
public final int LATTE = 1;
А потом применять их в коде. Код будет более четабильным и не нужны поясняющие комменты

2021-10-31 10:57 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +                machineMoney += 6;
Вообще, попробуй вынести все константы в отдельный класс и уже через него можешь обращатся к ним
Сделай их все public static final (int/String) NAME = ...;
Например:
public class Values{
public static final int MIN_CAPUCHINO_WATER = 200;
public static final int MIN_CAPUCHINO_MILK= 100;
...
}
.....
.....
if (machineWater >= Values.MIN_CAPUCHINO_WATER && 
machineMilk >= Values.MIN_CAPUCHINO_MILK && 
machineCoffeeBeans >=Values.MIN_CAPUCHINO_COFFEE_BEANS){
........
}
.....
В этот класс можно также поместить enum State

Полезная ссылка: https://www.baeldung.com/java-constants-good-practices

2021-11-01 11:52 UTC, ikalegin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +                machineMoney += 6;
@maxsomochkin, значения лучше реализовать в отдельном файле с названием Values.java или сделать это в файле с классом кофемашины?

2021-11-13 14:20 UTC, asrubel approved these changes

2021-11-13 14:20 UTC, asrubel reviewed
Коммиты не забудь сжать

2021-11-14 01:50 UTC, merged